language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -U pip setuptools wheel
  - pip install 'tox>=2.0.0,<3.0.0' 'tox-travis>=0.8,<1.0'
script:
  - tox
notifications:
  slack:
    secure: rMqJ2wZxLD1bDsHjfl43CV7arHtNRsm63bmXsqgK2XZV1tw8DG4+FHACATLKjHLWImLUhurWwGd0ba0vzf2MngOfQC8dH71EoBJpgAQK8h5WlZc+Fqc+1r8jWMSqFrWhWyIGs7Dl4YTI9FzDxpHeIgmN0MsYyYqhELPVTyZBDKSREQKtK3LfS+RKdhvsHOhAia/eUceMN4idgcOoeveTy5SLynlY+N15f3W2gP5ZQuTkeGsIcRnXRyFxuKBv1GkNqF4mEZwuzX9NRTU5UgAVum6tDdWRlXQ3CAq+CPsPSJhxXHKBj0mdrfZFve2KmTA7RMqo0Aoafk90j8F18CxgCQsS2KIPekMwk8z0Cg2wV6kHzgDIodwonFedIayzXFDr3Zt8BYHUQ2Fh/UioW84Yo65kKV+T7KYSqLq6XNP/kz92reC/n9KHAXAxaX8F3LLre0kcik3Q0Hewx3AajGiw/mgMeFkt/7wWImsONhHSDv5MDkl7233CuN15kTv8ig2evxigFjC6a3MaMEH92QV8meBFNoRo+i/35ypYA1YWDpqpFIxFQV8Y4fu4gkxI6DxNlzhZJjbUwQyUsKqPMERwyKOzZwQXg2RiT70sTPqnyHPkQUwKC2z0ig+yU0N72uMt2RZbvT728N28BynVlibQtD0G/C9TskliA67OmgzTd4w=
